### PR TITLE
Service-detail

### PR DESCRIPTION
**Pull request by rivettp**
Fixes to the original ontology.
Expand out the subclasses of DataService.

### CODE REVIEW

**Comment by nvar** [comment]
@rivettp  I propose to have the prefix dprod with # similar with dcat http://www.w3.org/ns/dcat# but the dprod ontology itself has different uri. All artifacts defined in the ontology will have the isDefinedBy to the ontology uri
Is that something that you can change please?

**Comment by FroehlichMarcel** [comment]
It is intentional to use / instead of #
There are number of reasons that tools work much more performant on data if
the concept of fragment in IRIs is dropped.

Cheers, Marcel

nvar ***@***.***> schrieb am Fr. 15. Sept. 2023 um 18:27:

**Comment by nvar** [comment]
I prefer also the use of / instead of # so let's use that although dcat uses # 

So let's start with:

prefix dprod: <https://w3id.org/dprod/> .


However we have two options 1. Different uris in the ontology so we can use versioning and we don't necessarily need content negotiation 2. The prefix is the same with the ontology so we need content negotiation for versioning

I have worked always with 1 and preferred to have a different prefix for the ontology and rdfs:isDefinedBy for all ontology artifacts 

prefix dprod: <https://w3id.org/dprod/> .

<https://w3id.org/schema/1.0.0./dprod/>
   a owl:Ontology ;

dprod:Dataset-distribution a sh:PropertyShape;
rdfs:isDefinedBy <https://w3id.org/schema/1.0.0./dprod/> 

That way even if all ontologies fall in the same graph we can always recreate

**Comment by FroehlichMarcel** [comment]
👍

Am Sa., 16. Sept. 2023 um 10:47 Uhr schrieb nvar ***@***.***>:

**Comment by rivettp** [comment]
For (future) tracking of versioning there is the owl:versionIRI property.
What we have done for a bunch of other ontologies, including FIBO, is to have the latest version at (in our case) https://w3id.org/dprod/  and also its specific versionIRI e.g. https://w3id.org/dprod/1.0/ (we'd need to decide on a scheme).
Note that for each such accessible version we'd need to update the .htaccess file at w3id.org via a PR.

**Comment by nvar** [comment]
@rivettp  did you manage to merge your branch? When you do please let me know so I can add some properties for the SLAs

**Comment by nvar** [comment]
@rivettp  I merged it

**Pull request merged**
